### ISSUE TITLE
[Enhancement]: Update terraform-provider-aws to v5.82.2

### ISSUE THREAD

**Issue by larhauga** [upbound/terraform-provider-aws#280]
### Description

Hi,
could you make a new branch for the v5.82.2 terraform provider? The new version contains a new bedrock inference profile resource which we would like to use. 
Since this requires new branches in this repository, I were unable to contribute this work.

Based on previous sync work: https://github.com/upbound/terraform-provider-aws/pull/278

```
git fetch upbound
git fetch hashicorp

BUMP_FROM="v5.73.0"
BUMP_TO="v5.78.0"

git checkout "$BUMP_TO"
git checkout -b "upjet-$BUMP_TO"
git push upbound "upjet-$BUMP_TO"

git reset --hard "upbound/upjet-$BUMP_FROM"
git rebase "$BUMP_TO"

make
git push origin "upjet-$BUMP_TO"
```

To summarize:

1. Fetch upstreams.
1. Prepare and push an “empty” branch (upjet-v5.78.0 for this PR), against which we'll open the PR.
1. Reset to our previous version bump (upbound/upjet-v5.73.0 for this PR).
1. Rebase onto upstream's target version tag (hashicorp/v5.78.0 for this PR).
1. Build, to make sure that it works.
1. Finally, push to origin (turkenf/upjet-v5.78.0 for this PR).
1. Set base branch to upjet-v5.78.0 while opening the PR in GitHub.

### Would you like to implement a fix?

No

**Comment by mergenci** [comment]
Thanks for your interest @larhauga 🙌 There are not many people who are aware of this fork 🙂 We could definitely improve our workflow to invite contributions, but this fork is supposed to be an implementation detail. We don't want the maintenance work required here to be substantive either, so provider-upjet-aws maintainers are likely to be the only ones to maintain this repository. Can you open an issue in [provider-upjet-aws](https://github.com/crossplane-contrib/provider-upjet-aws/issues) for your request? We try to keep up-to-date with Terraform provider version bumps regularly, in a month or so. Nevertheless, letting us know that you are waiting for one helps us prioritize accordingly.
